arange()함수를 이용하여 배열 생성

ndim:배열의 차수, shape:3*5, dtype.name : 데이터형식

dtype.itemsize : 각 데이터의 저장 사이즈, size: 배열의 총 데이터 갯수

In [2]:
import numpy as np
# arange()함수를 이용하여 배열 생성
arr = np.arange(15)
print(arr, arr.ndim,"차원",arr.shape)
# .ndim 차원, .shape 배열의 사이즈
print()
arr2 = arr.reshape(3,5) #배열의 차수를 변경
print(arr2, arr2.ndim,"차원",arr2.shape)
print(arr.dtype.name, arr2.dtype.itemsize, arr2.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14] 1 차원 (15,)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 2 차원 (3, 5)
int32 4 15


In [14]:
a = np.arange(-5,5,0.5)
a.size
arr = a.reshape(int(a.size/4), 4)
arr

array([[-5. , -4.5, -4. , -3.5],
       [-3. , -2.5, -2. , -1.5],
       [-1. , -0.5,  0. ,  0.5],
       [ 1. ,  1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ,  4.5]])

In [15]:
b = np.array([1,2,3,4])
type(b)

numpy.ndarray

In [16]:
a_list = [[1,2,3],[4,5,6]]
print(a_list, type(a_list))

[[1, 2, 3], [4, 5, 6]] <class 'list'>


In [18]:
a_arr = np.array(a_list)
print(a_arr, type(a_arr))

[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'>


In [24]:
# 1부터 100까지의 수를 리스트로 만든 후 5*4*5 의 배열로 변경
arr = np.array(list(range(1,101))).reshape(5,4,5)
arr
arr.flatten() #평탄화(1차원으로 변경)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [21]:
arr.ndim #차원 알아보기

3

In [22]:
arr.reshape(5*4*5)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [5]:
# 초기값을 부여하면서 배열 생성하기
# 초기값을 0로
np.zeros(5) #1차원 배열 5인 ->초기값이 0
np.zeros(2,3,5)#배열의 차원은 tuple로
np.zeros((5,2), dtype="i") #값을 정수형으로 사이즈는 32bit
np.zeros(5,dtype="U4") #값의 형식이 문자, null이 초기화 됨
np.zeros(5,dtype='i8') #64bit
np.zeros(5,dtype='f') #float 32
np.ones(5,dtype='f') #float 32, 1로 초기화
no.ones_like(np.zeros((5,2),dtype="i",dtype="f"))
np.empty(4,3)


TypeError: Cannot interpret '3' as a data type

In [6]:
print(x1+y1)
print(x1+y1)
print(x1*y1)


NameError: name 'x1' is not defined

In [7]:
print(x2 + z1)
print(x1 ** 2)
print(x1 >= 2)

NameError: name 'x2' is not defined

In [8]:
print(x2.ndim,x2)
x2.flatten{}

SyntaxError: invalid syntax (Temp/ipykernel_14856/2337244425.py, line 2)

In [9]:
arr = np.arange(10) ** 2
print(arr)
print(arr[2])
print(arr[3:7])
print(arr[0:-1:2])
print(arr[::-1])
for data in arr:
    print(data)


[ 0  1  4  9 16 25 36 49 64 81]
4
[ 9 16 25 36]
[ 0  4 16 36 64]
[81 64 49 36 25 16  9  4  1  0]
0
1
4
9
16
25
36
49
64
81


In [14]:
arr = np.arange(1,20+1,1).reshape(5,4)
print(arr)
print(arr[1,1], arr[3,2], arr[[1,3],[1,2]])
#        행,열     행,열      행s  , 열s
print(arr[1:3, :])
print(arr[:, -1])
arr[1,:] *= -1
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
6 15 [ 6 15]
[[ 5  6  7  8]
 [ 9 10 11 12]]
[ 4  8 12 16 20]
[[ 1  2  3  4]
 [-5 -6 -7 -8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [17]:
# np의 일반함수 : np.arange(), np.sin(a)
np.sin(arr)
np.log(np.arange(0.0,1,0.05))

C:\Users\wpgud\AppData\Local\Temp/ipykernel_14856/103171832.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(np.arange(0.0,1,0.05))


array([       -inf, -2.99573227, -2.30258509, -1.89711998, -1.60943791,
       -1.38629436, -1.2039728 , -1.04982212, -0.91629073, -0.7985077 ,
       -0.69314718, -0.597837  , -0.51082562, -0.43078292, -0.35667494,
       -0.28768207, -0.22314355, -0.16251893, -0.10536052, -0.05129329])

In [23]:
# maximum, minimum, sum, argmax
a1 = np.array([1,7,3])
a2 = np.array([3,4,5])
print(np.maximum(a1,a2))
print(np.minimum(a1,a2))
print(np.sum(a1))
print(np.argmax(a1)) # max값이 위치한 위치 반환
print(np.argmin(a2)) # min값이 위치한 위치 반환

[3 7 5]
[1 4 3]
11
1
0


# random 함수

In [25]:
np.random.seed(0)
np.random.choice(100,5) # 0~100 사이의 수 중에서 5개 선택
np.random.rand(2,3) # 0에서 1 사이의 수를 2*3으로 선택 (총 6개의 수)
np.random.randn(2,3) # -무한대에서 +무한대 사이의 수를 표준정규분포 형태로 랜덤 추출

array([[-0.19908439, -0.07804325,  0.43398609],
       [-0.49764631, -1.07672068, -0.56992347]])

In [26]:
a = np.array([[0.1,0.8,0.2],[0.3,0.2,0.5],[0.9,0.5,0.3]])
np.argmax(a, axis =0)

array([2, 0, 1], dtype=int64)

In [29]:
# 통계함수 : count(), mean(), median(), var(), std(), max(), min(), percentile()
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])
print(len(x),np.mean(x)) # 개수, 평균
print(np.median(x), np.var(x), np.std(x), np.max(x))
print(np.min(x), np.percentile(x, 25),np.percentile(x, 75),np.percentile(x, 100))

26 4.8076923076923075
5.0 115.23224852071006 10.734628476137871 23
-24 0.0 10.0 23.0


In [30]:
np.random.choice(10,5, replace=False) #중복 안됨, replace=True는 중복가능
np.random.choice(5,10, p=[0.1,0,0.3,0.6,0]) # 0,1,2,3,4에 대한 확률을 p에 입력


array([3, 0, 2, 2, 3, 3, 2, 2, 3, 3])

In [31]:
x

array([ 18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
         2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [33]:
np.random.shuffle(x)  #배열 재조합
x

array([ -6,   5,   2,  23,  23,   7,  15,  -8,   5,   0,  15,   0,  10,
         9,  19, -13,   8, -24,   5,  18,  -7,  10,   4,   2,  -1,   4])

In [34]:
np.random.choice(x,5, replace=False)

array([ 19,  18, -13,   7, -24])

In [104]:
# np.random.randint(low, high=None, size = None)
np.random.randint(10,size=10)
np.random.randint(10,30,size=10) #10은 나오고 30은 안나옴
np.random.randint(10,30,size=(3,5))

array([[12, 17, 22, 29, 18],
       [17, 14, 20, 25, 16],
       [27, 10, 17, 17, 19]])

In [98]:
# 다음 행렬과 같은 배열이 있다.
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,13, 14, 15, 16, 17, 18, 19, 20])

# 이 배열에서 3의 배수를 찾아라.
# 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
# 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
print(list(filter(lambda y:y%3==0,x)))
print(list(filter(lambda y:y%4==1,x)))
print(list(filter(lambda y:(y%3==0) & (y%4==1),x)))

[3, 6, 9, 12, 15, 18]
[1, 5, 9, 13, 17]
[9]
